// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBTAasGntwaGJxrhExoOdMnOhUE6sB6k',
    appId: '1:624171904398:web:8e5fb18e2986c1bb5788df',
    messagingSenderId: '624171904398',
    projectId: 'grocery-prokit-app',
    authDomain: 'grocery-prokit-app.firebaseapp.com',
    storageBucket: 'grocery-prokit-app.firebasestorage.app',
    measurementId: 'G-2MF13GTFRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmv-YK8TmPmhvIXv1PbwijQQ8cpCiYOmA',
    appId: '1:624171904398:android:0bfb5c9740f724b05788df',
    messagingSenderId: '624171904398',
    projectId: 'grocery-prokit-app',
    storageBucket: 'grocery-prokit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88cdmACjQyXBPsc4kiLAfzS_JtPA8VRI',
    appId: '1:624171904398:ios:d9cb1ecaa11f155b5788df',
    messagingSenderId: '624171904398',
    projectId: 'grocery-prokit-app',
    storageBucket: 'grocery-prokit-app.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC88cdmACjQyXBPsc4kiLAfzS_JtPA8VRI',
    appId: '1:624171904398:ios:d9cb1ecaa11f155b5788df',
    messagingSenderId: '624171904398',
    projectId: 'grocery-prokit-app',
    storageBucket: 'grocery-prokit-app.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLBTAasGntwaGJxrhExoOdMnOhUE6sB6k',
    appId: '1:624171904398:web:b611bc0cfa26485d5788df',
    messagingSenderId: '624171904398',
    projectId: 'grocery-prokit-app',
    authDomain: 'grocery-prokit-app.firebaseapp.com',
    storageBucket: 'grocery-prokit-app.firebasestorage.app',
    measurementId: 'G-JKFDMDRL1T',
  );
}
